function mask = get_roi_mask(FSID, partition)
	% get mask for partition
	[lh_mask, ~, ~] = cvnroimask(...
		FSID, ...
		'lh', ...
		partition, ...
		[], ...
		'DENSETRUNCpt' ...
	);
	[rh_mask, ~, ~] = cvnroimask(...
		FSID, ...
		'rh', ...
		partition, ...
		[], ...
		'DENSETRUNCpt' ...
	);
	mask = [lh_mask{1}; rh_mask{1}];
end
